exec sp_rename 'FK_ReclamationAgreementProject_ProjectID_ProjectID', 'FK_ReclamationAgreementProject_Project_ProjectID', 'OBJECT'
exec sp_rename 'FK_ReclamationAgreementPacificNorthActivity_ReclamationAgreementID_ReclamationAgreement_ReclamationAgreementID', 'FK_ReclamationAgreementPacificNorthActivity_ReclamationAgreement_ReclamationAgreementID', 'OBJECT'
exec sp_rename 'FK_ReclamationAgreementProject_ReclamationAgreementID_ReclamationAgreement_ReclamationAgreementID', 'FK_ReclamationAgreementProject_ReclamationAgreement_ReclamationAgreementID', 'OBJECT'
exec sp_rename 'FK_ReclamationAgreementPacificNorthActivity_ReclamationPacificNorthActivityListID_ReclamationPacificNorthActivityListID', 'FK_ReclamationAgreementPacificNorthActivity_ReclamationPacificNorthActivityList_ReclamationPacificNorthActivityListID', 'OBJECT'

exec sp_rename 'FK_ReclamationAgreementReclamationCostAuthority_ReclamationAgreementID_ReclamationAgreement_ReclamationAgreementID', 'FK_ReclamationAgreementReclamationCostAuthority_ReclamationAgreement_ReclamationAgreementID', 'OBJECT'
exec sp_rename 'FK_ReclamationAgreementReclamationCostAuthority_ReclamationCostAuthorityID_ReclamationCostAuthorityID', 'FK_ReclamationAgreementReclamationCostAuthority_ReclamationCostAuthority_ReclamationCostAuthorityID', 'OBJECT'

