

exec sp_rename 'ImportFinancial.impApGenSheet.[PO Number - Key]', 'PONumberKey'
exec sp_rename 'ImportFinancial.impApGenSheet.[Purch Ord Line Itm - Key]', 'PurchOrdLineItmKey'
exec sp_rename 'ImportFinancial.impApGenSheet.[Reference - Key]', 'ReferenceKey'
exec sp_rename 'ImportFinancial.impApGenSheet.[Vendor - Key]', 'VendorKey'
exec sp_rename 'ImportFinancial.impApGenSheet.[Vendor - Text]', 'VendorText'
exec sp_rename 'ImportFinancial.impApGenSheet.[Fund - Key]', 'FundKey'
exec sp_rename 'ImportFinancial.impApGenSheet.[Funded Program - Key]', 'FundedProgramKey'
exec sp_rename 'ImportFinancial.impApGenSheet.[WBS Element - Key]', 'WBSElementKey'
exec sp_rename 'ImportFinancial.impApGenSheet.[WBS Element - Text]', 'WBSElementText'
exec sp_rename 'ImportFinancial.impApGenSheet.[Budget Object Class - Key]', 'BudgetObjectClassKey'
exec sp_rename 'ImportFinancial.impApGenSheet.[Debit Amount]', 'DebitAmount'
exec sp_rename 'ImportFinancial.impApGenSheet.[Credit Amount]', 'CreditAmount'
exec sp_rename 'ImportFinancial.impApGenSheet.[Debit/Credit Total]', 'DebitCreditTotal'


exec sp_rename 'ImportFinancial.impPayRecV3.[Business area - Key]', 'BusinessAreaKey'
exec sp_rename 'ImportFinancial.impPayRecV3.[FA Budget Activity - Key]', 'FABudgetActivityKey'
exec sp_rename 'ImportFinancial.impPayRecV3.[Functional area - Text]', 'FunctionalAreaText'
exec sp_rename 'ImportFinancial.impPayRecV3.[Obligation Number - Key]', 'ObligationNumberKey'
exec sp_rename 'ImportFinancial.impPayRecV3.[Obligation Item - Key]', 'ObligationItemKey'
exec sp_rename 'ImportFinancial.impPayRecV3.[Fund - Key]', 'FundKey'
exec sp_rename 'ImportFinancial.impPayRecV3.[Funded Program - Key (Not Compounded)]', 'FundedProgramKey'
exec sp_rename 'ImportFinancial.impPayRecV3.[WBS Element - Key]', 'WBSElementKey'
exec sp_rename 'ImportFinancial.impPayRecV3.[WBS Element - Text]', 'WBSElementText'
exec sp_rename 'ImportFinancial.impPayRecV3.[Budget Object Class - Key]', 'BudgetObjectClassKey'
exec sp_rename 'ImportFinancial.impPayRecV3.[Vendor - Key]', 'VendorKey'
exec sp_rename 'ImportFinancial.impPayRecV3.[Vendor - Text]', 'VendorText'
exec sp_rename 'ImportFinancial.impPayRecV3.[Goods Receipt]', 'GoodsReceipt'
exec sp_rename 'ImportFinancial.impPayRecV3.[Unexpended Balance]', 'UnexpendedBalance'