exec sp_rename 'Reclamation.FK_AgreementRequest_Organization_RecipientOrganizationID_OrganizationID', 'FK_ObligationRequest_Organization_RecipientOrganizationID_OrganizationID', 'OBJECT'
exec sp_rename 'Reclamation.FK_AgreementRequest_Person_CreatePersonID_PersonID', 'FK_ObligationRequest_Person_CreatePersonID_PersonID', 'OBJECT'
exec sp_rename 'Reclamation.FK_AgreementRequest_Person_TechnicalRepresentativePersonID_PersonID', 'FK_ObligationRequest_Person_TechnicalRepresentativePersonID_PersonID', 'OBJECT'
exec sp_rename 'Reclamation.FK_AgreementRequest_Person_UpdatePersonID_PersonID', 'FK_ObligationRequest_Person_UpdatePersonID_PersonID', 'OBJECT'
exec sp_rename 'Reclamation.FK_AgreementRequest_Agreement_AgreementID', 'FK_ObligationRequest_Agreement_AgreementID', 'OBJECT'
exec sp_rename 'Reclamation.FK_AgreementRequest_ContractType_ContractTypeID', 'FK_ObligationRequest_ContractType_ContractTypeID', 'OBJECT'
exec sp_rename 'Reclamation.FK_AgreementRequest_AgreementRequestFundingPriority_ReclamationAgreementRequestFundingPriorityID_AgreementRequestFundingPriority', 'FK_ObligationRequest_ObligationRequestFundingPriority_ReclamationObligationRequestFundingPriorityID_ObligationRequestFundingPrio', 'OBJECT'
exec sp_rename 'Reclamation.FK_AgreementRequest_AgreementRequestStatus_AgreementRequestStatusID', 'FK_ObligationRequest_ObligationRequestStatus_ObligationRequestStatusID', 'OBJECT'


exec sp_rename 'Reclamation.PK_AgreementRequest_AgreementRequestID', 'PK_ObligationRequest_ObligationRequestID', 'OBJECT'
exec sp_rename 'Reclamation.PK_AgreementRequestFundingPriority_AgreementRequestFundingPriorityID', 'PK_ObligationRequestFundingPriority_ObligationRequestFundingPriorityID', 'OBJECT'
exec sp_rename 'Reclamation.PK_AgreementRequestStatus_AgreementRequestStatusID', 'PK_ObligationRequestStatus_ObligationRequestStatusID', 'OBJECT'