--begin tran

exec sp_rename 'dbo.FK_GeospatialAreaType_GeospatialAreaType_EsuDpsGeospatialAreaTypeID', 'FK_GeospatialAreaType_GeospatialAreaType_EsuDpsGeospatialAreaTypeID_GeospatialAreaTypeID', 'OBJECT'
go
exec sp_rename 'dbo.FK_GeospatialAreaType_GeospatialAreaType_EsuDpsGeospatialAreaTypeID_TenantID', 'FK_GeospatialAreaType_GeospatialAreaType_EsuDpsGeospatialAreaTypeID_TenantID_GeospatialAreaTypeID_TenantID', 'OBJECT'
go

exec sp_rename 'dbo.FK_GeospatialAreaType_GeospatialAreaType_MPGGeospatialAreaTypeID', 'FK_GeospatialAreaType_GeospatialAreaType_MPGGeospatialAreaTypeID_GeospatialAreaTypeID', 'OBJECT'
go
exec sp_rename 'dbo.FK_GeospatialAreaType_GeospatialAreaType_MPGGeospatialAreaTypeID_TenantID', 'FK_GeospatialAreaType_GeospatialAreaType_MPGGeospatialAreaTypeID_TenantID_GeospatialAreaTypeID_TenantID', 'OBJECT'
go
exec sp_rename 'dbo.FK_GeospatialAreaType_GeospatialAreaType_PopulationGeospatialAreaTypeID', 'FK_GeospatialAreaType_GeospatialAreaType_PopulationGeospatialAreaTypeID_GeospatialAreaTypeID', 'OBJECT'
go
exec sp_rename 'dbo.FK_GeospatialAreaType_GeospatialAreaType_PopulationGeospatialAreaTypeID_TenantID', 'FK_GeospatialAreaType_GeospatialAreaType_PopulationGeospatialAreaTypeID_TenantID_GeospatialAreaTypeID_TenantID', 'OBJECT'
go
--rollback tran